### ISSUE TITLE
question: is /data used for anything in the default configuration?

### ISSUE THREAD

**Issue by stefanfoulis** [timhaak/docker-sickbeard#5]
... or do I need to configure sickbeard to use ``/data`` for various things manually over the web-interface or by editing ``/config/config.ini``?

**Comment by ryankevans** [comment]
This volume is meant to be used as the place where your shows reside.  It isn't used out of the box, because the initial configuration doesn't come with any shows configured.  You'd map this volume to your "tv" directory, and then use "/data/SOME_SHOW_NAME" in the web interface when going through "Add Show" wizard.

Perhaps we should supply a modified default config.ini that uses /data for the "root_dirs" variable, which may then pre-populate some fields in the web interface with a reasonable default - but I'd have to dig in and make sure that's what this variable is meant for.

**Comment by timhaak** [comment]
Hi yes I basically point it at the directory my shows are in that It need to keep track of. 

The config dir given is for storing config.

Basically with data it more just effectively mounting it into the cotainer so that sickbeard can see it.

You still need to log into sickbeard and set the config to point at /data/my_dir

The reason for not doing it automatically a I'm lazy :) and b there are a couple different directories that you would have to set up mount points for depending on what the user has decided to configure. ie Dir for nzb files, directory for torrent files. 

For me the all exist in data so by mounting the one I can get to any of them via the web interface. Once the config is set all the work is done.

**Comment by timhaak** [comment]
I'm gong to close this as not  sure what extra stefanfoulis wanted?

**Comment by stefanfoulis** [comment]
thanks for the reply :-)
